In [28]:
import tensorflow as tf
from tensorflow.keras import datasets, layers, models
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [29]:
path_to_raw_data = "../data/raw/Kannada-MNIST/"

In [30]:
df_raw_train = pd.read_csv(path_to_raw_data + "train.csv")
df_raw_test = pd.read_csv(path_to_raw_data + "test.csv")

In [31]:
df_raw_train.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [32]:
df_raw_test.head()

,id,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [33]:
feature_cols = ["pixel{i}".format(i=i) for i in range(784)]
target_col = "label"

In [ ]:
x_train = df_raw_train[feature_cols].values.reshape(-1, 28, 28, 1)
y_train = df_raw_train[[target_col]].values.flatten()

x_test = df_raw_test[feature_cols].values.reshape(-1, 28, 28, 1)

In [ ]:
print(np.shape(x_train))

In [ ]:
x_train_train, x_train_eval, y_train_train, y_train_eval = train_test_split(x_train, y_train, test_size=0.33, random_state=42)

In [ ]:
# Training Parameters
learning_rate = 0.001
num_steps = 2000
batch_size = 128

# Network Parameters
num_input = 784 # MNIST data input (img shape: 28*28)
num_classes = 10 # MNIST total classes (0-9 digits)
dropout = 0.25 # Dropout, probability to drop a unit

In [ ]:
model = models.Sequential()
model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.Flatten())
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))

In [ ]:
model.summary()

In [ ]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [ ]:
history = model.fit(x_train_train, y_train_train, epochs=10, 
                    validation_data=(x_train_eval, y_train_eval))

In [ ]:
np.shape(x_test)

In [ ]:
tf.test.is_gpu_available(
    cuda_only=False,
    min_cuda_compute_capability=None
)

In [ ]:
tf.test.is_built_with_cuda()

In [ ]:
y_test = model.predict_classes(tf.cast(x_test, tf.float32))

In [ ]:
df_prediction = pd.DataFrame({'id' : df_raw_test["id"], 'label' : y_test})

In [ ]:
df_prediction.head()

In [ ]:
df_prediction.to_csv("../data/processed/Kannada-MNIST/result_cnn_1.csv", index=False)